// Package staticassets embeds the frontend assets internal/router.New
// serves at `/static/...`: dist/ (esbuild's JS bundles + Tailwind's
// compiled app.css, docs/components/overview.md §1, §6), img/ (the app
// logo, issue #238) and vendor/ (the checked-in htmx.min.js). Embedding
// them lets cmd/server and cmd/desktop serve `/static/...` from a single
// self-contained binary
// once packaged, without depending on static/src's absolute path on disk
// (internal/router.go's now-removed staticDir, issue #59).
//
// The go:embed directive can only reference paths under this file's own directory (no
// `..`), which is why this package lives inside static/src rather than
// internal/router. It also fails to compile if a target directory
// contains no files: dist/ is generated by `bun run --cwd static build`
// (`.gitignore`'d, absent in a clean checkout) and is deliberately not
// checked into git, so this package - and therefore `go build ./...` -
// refuses to compile until that frontend build has actually run. That is
// the intended forcing function for CI's `build` (and `lint`/`test`)
// jobs to run the frontend build before any Go compilation step.
package staticassets

import "embed"

//go:embed dist img vendor
var FS embed.FS
